package mobile_refueling_dev.pages.Locators;

public class LocatorsOfMerchantRegistration {
    public static final String MERCHANT_MANAGEMENT_MENU = "//li[@title='Merchant Management']//div[@class='ant-menu-submenu-title']";
    public static final String MERCHANT_SUB_MENU = "//li[@title='Merchants']//a[contains(text(),'Merchants')]";
    public static final String ADD_MERCHANT_BUTTON = "//span[normalize-space()='Add Merchant']";
    public static final String EMAIL_FIELD = "//input[@type='email']";
    public static final String PHONE_CODE_DROPDOWN = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[2]/div[1]/uni-email-phone-control[1]/div[1]/nz-form-item[2]/nz-form-control[1]/div[1]/div[1]/nz-input-group[1]/span[1]/span[1]/nz-select[1]/nz-select-top-control[1]";
    public static final String PHONE_CODE = "//html[1]/body[1]/div[1]/div[2]/div[1]/nz-option-container[1]/div[1]/cdk-virtual-scroll-viewport[1]/div[1]/nz-option-item[1]";
    public static final String PHONE_NUMBER_1 = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[2]/div[1]/uni-email-phone-control[1]/div[1]/nz-form-item[2]/nz-form-control[1]/div[1]/div[1]/nz-input-group[1]/span[1]/input[1]";
    public static final String MERCHANT_TYPE_DROPDOWN_FIELD = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/nz-form-item[1]/nz-form-control[1]/div[1]/div[1]/nz-select[1]/nz-select-top-control[1]/nz-select-search[1]/input[1]";
    public static final String MERCHANT_TYPE = "//html[1]/body[1]/div[1]/div[2]/div[1]/nz-option-container[1]/div[1]/cdk-virtual-scroll-viewport[1]/div[1]/nz-option-item[1]/div[1]";
    public static final String MERCHANT_NAME_FIELD = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/nz-form-item[2]/nz-form-control[1]/div[1]/div[1]/input[1]";
    public static final String ADDRESS_1 = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/nz-form-item[4]/nz-form-control[1]/div[1]/div[1]/input[1]";
    public static final String TAX_PAYER_ID = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/nz-form-item[9]/nz-form-control[1]/div[1]/div[1]/input[1]";
    public static final String START_TIME = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/nz-form-item[10]/nz-form-control[1]/div[1]/div[1]/nz-time-picker[1]/div[1]/input[1]";
    public static final String CONTACT_FIRST_NAME = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/nz-form-item[14]/nz-form-control[1]/div[1]/div[1]/input[1]";
    public static final String CONTACT_LAST_NAME = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/nz-form-item[15]/nz-form-control[1]/div[1]/div[1]/input[1]";
    public static final String CONTACT_EMAIL = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/nz-form-item[16]/nz-form-control[1]/div[1]/div[1]/input[1]";
    public static final String BANK_DROPDOWN = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/form[1]/div[1]/div[1]/div[1]/nz-form-item[1]/nz-form-control[1]/div[1]/div[1]/nz-select[1]/nz-select-top-control[1]/nz-select-search[1]/input[1]";
    public static final String SELECT_BANK = "//html[1]/body[1]/div[1]/div[2]/div[1]/nz-option-container[1]/div[1]/cdk-virtual-scroll-viewport[1]/div[1]/nz-option-item[2]/div[1]";
    public static final String BRANCH_DROPDOWN = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/form[1]/div[1]/div[1]/div[1]/nz-form-item[2]/nz-form-control[1]/div[1]/div[1]/nz-select[1]/nz-select-top-control[1]/nz-select-search[1]/input[1]";
    public static final String SELECT_BRANCH = "//html[1]/body[1]/div[1]/div[2]/div[1]/nz-option-container[1]/div[1]/cdk-virtual-scroll-viewport[1]/div[1]/nz-option-item[1]/div[1]";
    public static final String ACCOUNT_NUMBER = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/form[1]/div[1]/div[1]/div[1]/nz-form-item[3]/nz-form-control[1]/div[1]/div[1]/input[1]";
    public static final String ADD_BANK_FOR_MERCHANT = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[3]/form[1]/div[1]/div[1]/div[1]/nz-form-item[4]/nz-form-control[1]/div[1]/div[1]/div[1]/div[1]/button[1]";
    public static final String SAVE_BUTTON = "//html[1]/body[1]/uni-root[1]/uni-dashboard[1]/nz-spin[1]/div[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/nz-spin[1]/div[1]/div[1]/uni-merchant-editor[1]/nz-spin[1]/div[1]/form[1]/div[4]/button[1]";
    public static final String OK_BUTTON = "//html[1]/body[1]/div[1]/div[3]/div[1]/nz-modal-container[1]/div[1]/div[1]/div[2]/button[1]";
    public static final String TEXT_ASSERT = "//p[@class='modal-content']";
}
